/*const MESSAGES = {

	COMMANDS : {

		ADMIN : {

			RELOAD: {
				name: "reload",
				aliases: ["r"],
				category: "admin",
				description: "Éteint le bot",
				cooldown: 0,
				usage: "",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},

			RELOADCOMMAND: {
				name: "reloadcommand",
				aliases: ["rc"],
				category: "admin",
				description: "Actualise une cmd.",
				cooldown: 0,
				usage: "<command_name>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},

			DROLESPAM : {
				name: "DroleSpam",
				aliases: ["spam"],
				category: "admin",
				description: "Spam MP",
				cooldown: 0,
				usage: "<pseudo>",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},
		},

		MISC : {

			SAY: {
				name: "say",
				aliases: ["repeat", "rep"],
				category: "misc",
				description: "Répète du texte.",
				cooldown: 10,
				usage: "<votre_message>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},

			PING: {
				name: "ping",
				aliases: ["pong"],
				category: "misc",
				description: "Donne le ping du serveur.",
				cooldown: 10,
				usage: "",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},

			HELP: {
				name: "help",
				aliases: ["aide"],
				category: "misc",
				description: "Envoit la page d'aide aux commandes.",
				cooldown: 0,
				usage: "<commande_name>",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},
		},

		MODERATION : {

			BAN: {
				name: "ban",
				aliases: ["bannir"],
				category: "moderation",
				description: "Bannit un utilisateur.",
				cooldown: 0,
				usage: "<@user> <raison>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},

			KICK: {
				name: "kick",
				aliases: ["expulser"],
				category: "moderation",
				description: "Expulse un utilisateur.",
				cooldown: 0,
				usage: "<@user> <raison>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},

			MUTE: {
				name: "mute",
				aliases: ["taire"],
				category: "moderation",
				description: "Enlève le droit de parole à un utilisateur.",
				cooldown: 0,
				usage: "<@user> <time> <raison>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},

			PRUNE: {
				name: "prune",
				aliases: [""],
				category: "moderation",
				description: "Supprime un nombre de message spécifique d'un utilisateur.",
				cooldown: 0,
				usage: "<@user> <nbr_msg>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},

			PURGE: {
				name: "purge",
				aliases: ["clear"],
				category: "moderation",
				description: "Supprime un nombre de message spécifique.",
				cooldown: 0,
				usage: "<nbr_msg>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},

			UNBAN: {
				name: "unban",
				aliases: ["debannir"],
				category: "moderation",
				description: "Dé-bannit un utilisateur.",
				cooldown: 0,
				usage: "<id_user>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},

			UNMUTE: {
				name: "unmute",
				aliases: ["ping"],
				category: "moderation",
				description: "Rends le droit de parole à un utilisateur.",
				cooldown: 0,
				usage: "<@user>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},

			CLEAR: {
				name: "clear",
				aliases: ["clear"],
				category: "moderation",
				description: "Supprime un nombre de message spécifique.",
				cooldown: 0,
				usage: "<nbr_msg>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},

			ADDROLE: {
				name: "addrole",
				aliases: ["add"],
				category: "moderation",
				description: "Ajoute un rôle.",
				cooldown: 0,
				usage: "<@user> <role>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},

			REMOVEROLES: {
				name: "removeroles",
				aliases: ["removes"],
				category: "moderation",
				description: "Supprime plusieurs rôles.",
				cooldown: 0,
				usage: "<@user> <role1> <role2>",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},

			REMOVEROLE: {
				name: "removeroles",
				aliases: ["remove"],
				category: "moderation",
				description: "Supprime un rôle.",
				cooldown: 0,
				usage: "<@user> <role>",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},

			ADDROLES: {
				name: "addroles",
				aliases: ["adds"],
				category: "moderation",
				description: "Ajoute plusieurs rôles.",
				cooldown: 0,
				usage: "<@user> <role1> <role2>",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},
		},

		NATIONSGLORY : {

			FACE2D: {
				name: "face2d",
				aliases: ["faceskin2", "head2", "tete2", "skinface2"],
				category: "nationsglory",
				description: "Renvoit la tête d'un joueur en 2D.",
				cooldown: 10,
				usage: "<pseudo>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},

			FACE3D: {
				name: "face3d",
				aliases: ["faceskin3", "head3", "tête3", "skinface3"],
				category: "nationsglory",
				description: "Renvoit la tête d'un joueur en 3D.",
				cooldown: 10,
				usage: "<pseudo>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},

			COUNTRYADD: {
				name: "countryadd",
				aliases: ["ajouter", "add"],
				category: "nationsglory",
				description: "Ajoute une nation de la DB.",
				cooldown: 0,
				usage: "<country_name>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},

			COUNTRYREMOVE: {
				name: "countryremove",
				aliases: ["supprimer", "remove"],
				category: "nationsglory",
				description: "Supprime une nation de la DB.",
				cooldown: 0,
				usage: "<country_name>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},

			COUNTRYLIST: {
				name: "countrylist",
				aliases: ["countries","nations", "list"],
				category: "nationsglory",
				description: "Affiche la liste des nations.",
				cooldown: 0,
				usage: "<country_name>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},

			COUNTRYSEARCH: {
				name: "countrysearch",
				aliases: ["sc","chercher", "search"],
				category: "nationsglory",
				description: "Cherche une nation.",
				cooldown: 0,
				usage: "<country_name>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},

			RADIO: {
				name: "radio",
				aliases: ["ngradio","ngplay", "ecouteur", "listen"],
				category: "nationsglory",
				description: "Lance la radio (si dans un salon vocal).",
				cooldown: 10,
				usage: "",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},

			STOP: {
				name: "stop",
				aliases: ["ngstop", "eteindre"],
				category: "nationsglory",
				description: "Eteint la radio (si lancée).",
				cooldown: 10,
				usage: "",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},

			BODY: {
				name: "body",
				aliases: ["corps"],
				category: "nationsglory",
				description: "Renvoit le corps d'un utilisateur.",
				cooldown: 10,
				usage: "<pseudo>",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},
		},

		UTILITAIRES : {

			AVATAR: {
				name: "avatar",
				aliases: ["pp", "discord", "profil"],
				category: "utilitaires",
				description: "Renvoit une photo de profil discord.",
				cooldown: 3,
				usage: "<null>/<@user>",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},

			BOTINFO: {
				name: "botinfo",
				aliases: ["binfo", "infobot", "ibot"],
				category: "utilitaires",
				description: "Renvoit des infos sur le BOT.",
				cooldown: 10,
				usage: "",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},

			SERVER: {
				name: "server",
				aliases: ["skin", "servericon"],
				category: "utilitaires",
				description: "Renvoit une photo de serveur discord.",
				cooldown: 10,
				//usage: "<server_id>",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},

			SERVERINFO: {
				name: "serverinfo",
				aliases: ["sinfo", "infos", "infoserver", "servinfo", "infoserv"],
				category: "utilitaires",
				description: "Renvoit des infos sur le serveur.",
				cooldown: 10,
				usage: "<country_name>",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},

			SUGG: {
				name: "sugg",
				aliases: ["suggestion","idea"],
				category: "utilitaires",
				description: "Propose une suggestion.",
				cooldown: 10,
				usage: "<suggestion>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},
			TEAM: {
				name: "team",
				aliases: ["team"],
				category: "utilitaires",
				description: "Présente la team.",
				cooldown: 3,
				usage: "<TEAM>",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},
			USERINFO: {
				name: "userinfo",
				aliases: ["userinfo","user"],
				category: "utilitaires",
				description: "Renvoit des infos sur un utilisateurs.",
				cooldown: 10,
				usage: "<@user>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},
		},

		CONNECTIONS : {

			INSTA: {
				name: "insta",
				aliases: ["instagram"],
				category: "connections",
				description: "Renvoit un compte insta.",
				cooldown: 10,
				usage: "<pseudo>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},

			INVITE: {
				name: "invite",
				aliases: ["invitation", "inviter"],
				category: "connections",
				description: "Renvoit le lien d'dinvitation du BOT.",
				cooldown: 10,
				usage: "",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},

			MC: {
				name: "mc",
				aliases: ["minecraft", "mcraft", "minec"],
				category: "connections",
				description: "Permet de savoir si un serveur est connecté.",
				cooldown: 10,
				usage: "<server>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},
		},

		FUNNY : {

			BALL: {
				name: "ball",
				aliases: ["question"],
				category: "funny",
				description: "Réponds à une question.",
				cooldown: 10,
				usage: "<question>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},

			LOVE: {
				name: "love",
				aliases: ["amour", "loving"],
				category: "funny",
				description: "Permet de connaître notre compatibilité.",
				cooldown: 10,
				usage: "<@you> <@user>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},

			MEME: {
				name: "meme",
				aliases: ["image", "mème"],
				category: "funny",
				description: "Renvoit un mème.",
				cooldown: 10,
				usage: "",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},
		},
	},
};

exports.MESSAGES = MESSAGES;*/