const MESSAGES = {

	COMMANDS : {

		MISC : {

			REPORT: {
				name: "report",
				aliases: ["reporter"],
				category: "misc",
				description: "Signale le message d'un utilisateur.",
				cooldown: 0,
				usage: "<@user> <id_mess> <raison>",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},

			SAY: {
				name: "say",
				aliases: ["rep"],
				category: "misc",
				description: "Répète du texte.",
				cooldown: 0,
				usage: "<votre_message>",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},

			PING: {
				name: "ping",
				aliases: [""],
				category: "misc",
				description: "Donne le ping du serveur.",
				cooldown: 0,
				usage: "",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},

			HELP: {
				name: "help",
				aliases: ["aide"],
				category: "misc",
				description: "Envoit la page d'aide aux commandes.",
				cooldown: 0,
				usage: "<commande_name>",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},
		},

		ADMIN : {

			RELOAD: {
				name: "reload",
				aliases: ["eteindre"],
				category: "admin",
				description: "Éteint le bot",
				cooldown: 0,
				usage: "",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},

			RELOADCOMMAND: {
				name: "reloadcommand",
				aliases: ["rc"],
				category: "admin",
				description: "Actualise une cmd.",
				cooldown: 0,
				usage: "<command_name>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},

			DROLESPAM : {
				name: "DroleSpam",
				aliases: ["spam"],
				category: "admin",
				description: "Spam MP",
				cooldown: 0,
				usage: "<pseudo>",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},


			GHOST : {
				name: "ghost",
				aliases: ["ping"],
				category: "admin",
				description: "Ghost ping",
				cooldown: 0,
				usage: "<pseudo>",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},

      SERVER: {
				name: "server",
				aliases: ["icon"],
				category: "admin",
				description: "Renvoit une photo de serveur discord.",
				cooldown: 10,
				usage: "<server_id>",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},
		},

		MODERATION : {

			BAN: {
				name: "ban",
				aliases: ["bannir"],
				category: "moderation",
				description: "Bannit un utilisateur.",
				cooldown: 0,
				usage: "<@user> <raison>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},

			KICK: {
				name: "kick",
				aliases: ["expulser"],
				category: "moderation",
				description: "Expulse un utilisateur.",
				cooldown: 0,
				usage: "<@user> <raison>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},

			MUTE: {
				name: "mute",
				aliases: ["taire"],
				category: "moderation",
				description: "Enlève le droit de parole à un utilisateur.",
				cooldown: 0,
				usage: "<@user> <time> <raison>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},

			UNBAN: {
				name: "unban",
				aliases: ["deban"],
				category: "moderation",
				description: "Dé-bannit un utilisateur.",
				cooldown: 0,
				usage: "<id_user>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},

			UNMUTE: {
				name: "unmute",
				aliases: ["demute"],
				category: "moderation",
				description: "Rends le droit de parole à un utilisateur.",
				cooldown: 0,
				usage: "<@user>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},


			PURGE: {
				name: "purge",
				aliases: ["clear"],
				category: "moderation",
				description: "Supprime un nombre de message spécifique.",
				cooldown: 0,
				usage: "<nbr_msg>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},
			
			/*ADDROLE: {
				name: "addrole",
				aliases: ["add"],
				category: "moderation",
				description: "Ajoute un rôle.",
				cooldown: 0,
				usage: "<@user> <role>",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},

			REMOVEROLES: {
				name: "removeroles",
				aliases: ["rems"],
				category: "moderation",
				description: "Supprime plusieurs rôles.",
				cooldown: 0,
				usage: "<@user> <role1> <role2>",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},

			REMOVEROLE: {
				name: "removeroles",
				aliases: ["rem"],
				category: "moderation",
				description: "Supprime un rôle.",
				cooldown: 0,
				usage: "<@user> <role>",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},

			ADDROLES: {
				name: "addroles",
				aliases: ["adds"],
				category: "moderation",
				description: "Ajoute plusieurs rôles.",
				cooldown: 0,
				usage: "<@user> <role1> <role2>",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},*/
		},

		NATIONSGLORY : {

			FACE2D: {
				name: "face2d",
				aliases: ["2d"],
				category: "nationsglory",
				description: "Renvoit la tête d'un joueur en 2D.",
				cooldown: 10,
				usage: "<pseudo>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},

			FACE3D: {
				name: "face3d",
				aliases: ["3d"],
				category: "nationsglory",
				description: "Renvoit la tête d'un joueur en 3D.",
				cooldown: 10,
				usage: "<pseudo>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},

			COUNTRYADD: {
				name: "countryadd",
				aliases: ["cadd"],
				category: "nationsglory",
				description: "Ajoute une nation de la DB.",
				cooldown: 0,
				usage: "<country_name>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},

			COUNTRYREMOVE: {
				name: "countryremove",
				aliases: ["crem"],
				category: "nationsglory",
				description: "Supprime une nation de la DB.",
				cooldown: 0,
				usage: "<country_name>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},

			COUNTRYLIST: {
				name: "countrylist",
				aliases: ["clist"],
				category: "nationsglory",
				description: "Affiche la liste des nations.",
				cooldown: 0,
				usage: "<country_name>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},

			COUNTRYSEARCH: {
				name: "countrysearch",
				aliases: ["csearch"],
				category: "nationsglory",
				description: "Cherche une nation.",
				cooldown: 0,
				usage: "<country_name>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},

			RADIO: {
				name: "radio",
				aliases: ["ngradio"],
				category: "nationsglory",
				description: "Lance la radio (si dans un salon vocal).",
				cooldown: 10,
				usage: "",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},

			STOP: {
				name: "stop",
				aliases: ["ngstop", "eteindre"],
				category: "nationsglory",
				description: "Eteint la radio (si lancée).",
				cooldown: 10,
				usage: "",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},

			BODY: {
				name: "body",
				aliases: ["corps"],
				category: "nationsglory",
				description: "Renvoit le corps d'un utilisateur.",
				cooldown: 10,
				usage: "<pseudo>",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},

      PINGNG: {
				name: "ng",
				aliases: [""],
				category: "misc",
				description: "Donne le ping du serveur.",
				cooldown: 0,
				usage: "",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},
		},

		UTILITAIRES : {

			INFOBOT: {
				name: "infobot",
				aliases: ["infobot"],
				category: "utilitaires",
				description: "Donne des infos sur le BOT.",
				cooldown: 0,
				usage: "",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},

			INFOUSER: {
				name: "infouser",
				aliases: ["infosuer"],
				category: "utilitaires",
				description: "Donne des infso sur un utilisateur.",
				cooldown: 0,
				usage: "<@user>",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},

			INFOSERV: {
				name: "infoserv",
				aliases: ["infoserverv"],
				category: "utilitaires",
				description: "Donne des infos sur le serv.",
				cooldown: 0,
				usage: "",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},

			STATS: {
				name: "stats",
				aliases: ["rep"],
				category: "utilitaires",
				description: "Envoit des stats.",
				cooldown: 0,
				usage: "",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},

			POLL: {
				name: "poll",
				aliases: ["saondage"],
				category: "utilitaires",
				description: "Renvoit un saondage;",
				cooldown: 0,
				usage: "<sondage>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},

			AVATAR: {
				name: "avatar",
				aliases: ["pp"],
				category: "utilitaires",
				description: "Renvoit une photo de profil discord.",
				cooldown: 3,
				usage: "<null>/<@user>",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},

			BOTINFO: {
				name: "botinfo",
				aliases: ["botinfo"],
				category: "utilitaires",
				description: "Renvoit des infos sur le BOT.",
				cooldown: 10,
				usage: "",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},

			SERVERINFO: {
				name: "serverinfo",
				aliases: ["servinfo"],
				category: "utilitaires",
				description: "Renvoit des infos sur le serveur.",
				cooldown: 10,
				usage: "<country_name>",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},

			SUGG: {
				name: "sugg",
				aliases: ["idea"],
				category: "utilitaires",
				description: "Propose une suggestion.",
				cooldown: 10,
				usage: "<suggestion>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},
			TEAM: {
				name: "team",
				aliases: ["ekip"],
				category: "utilitaires",
				description: "Présente la team.",
				cooldown: 3,
				usage: "<TEAM>",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},
			USERINFO: {
				name: "userinfo",
				aliases: ["userinfo"],
				category: "utilitaires",
				description: "Renvoit des infos sur un utilisateurs.",
				cooldown: 10,
				usage: "<@user>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},
		},

		CONNECTIONS : {

			INSTA: {
				name: "insta",
				aliases: ["instagram"],
				category: "connections",
				description: "Renvoit un compte insta.",
				cooldown: 10,
				usage: "<pseudo>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},

			INVITE: {
				name: "invite",
				aliases: ["invitation"],
				category: "connections",
				description: "Renvoit le lien d'dinvitation du BOT.",
				cooldown: 10,
				usage: "",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},

			MC: {
				name: "mc",
				aliases: ["minecraft"],
				category: "connections",
				description: "Permet de savoir si un serveur est connecté.",
				cooldown: 10,
				usage: "<server>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},
		},

		FUNNY : {

			EIGHTBALL: {
				name: "8ball",
				aliases: ["question", "8"],
				category: "funny",
				description: "Réponds à une question.",
				cooldown: 0,
				usage: "<question ?>",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},
    		EMOJI: {
				name: "emoji",
				aliases: ["emoji"],
				category: "funny",
				description: "Affiche un emoji du bot",
				cooldown: 3,
				usage: "<emoji>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},

			LOVE: {
				name: "love",
				aliases: ["amour"],
				category: "funny",
				description: "Permet de connaître notre compatibilité.",
				cooldown: 5,
				usage: "<@user>",
				isUserAdmin: false,
				permissions: false,
				args: true,
			},

			MEME: {
				name: "meme",
				aliases: ["image"],
				category: "funny",
				description: "Renvoit un mème.",
				cooldown: 0,
				usage: "",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},
		},


		IMAGE : {

			PANDA: {
				name: "panda",
				aliases: [""],
				category: "image",
				description: "Renvoit une image de panda.",
				cooldown: 0,
				usage: "",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},

			CAT: {
				name: "cat",
				aliases: ["chat"],
				category: "image",
				description: "Renvoit une image de chat.",
				cooldown: 0,
				usage: "",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},

			DOG: {
				name: "dog",
				aliases: ["chien"],
				category: "image",
				description: "Renvoit une image de chien.",
				cooldown: 0,
				usage: "",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},

			FOX: {
				name: "fox",
				aliases: ["renard"],
				category: "image",
				description: "Renvoit une image de renard.",
				cooldown: 0,
				usage: "",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},

			ANIMEME: {
				name: "animeme",
				aliases: ["meme"],
				category: "image",
				description: "Renvoit un mème.",
				cooldown: 0,
				usage: "",
				isUserAdmin: false,
				permissions: false,
				args: false,
			},

		},

	},
};

exports.MESSAGES = MESSAGES;